name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global user.email "ishmamf2003@gmail.com"
          git config --global user.name "IshmamF"
          git push heroku ${HEROKU_DEFAULT_BRANCH_NAME}:refs/heads/${HEROKU_DEFAULT_BRANCH_NAME} --force
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "habit-heatmap-client" #Must be unique in Heroku
          heroku_email: "ishmamf2003@gmail.com"
