name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths: 
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "habit-heatmap-api"
          heroku_email: "ishmamf2003@gmail.com"
          appdir: "server"
      - name: deploy to heroku
        run: |
          git push heroku master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

      - name: Run Program
        run: python server.py
      
      - name: Run tests
        run: python -m pytest
          
