name: Run Frontend Test # frontend is deployed automatically on Vercel

on:
  push:
    branches: [ main ]
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [20.x, 21.x]
    steps:
      - uses: actions/checkout@v2
      - name: set config
        run: |
          git config --global user.name "Ishmam Fardin"
          git config --global user.email "ishmamf2003@gmail.com"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd controller && npm install
      - name: Build
        run: cd controller && CI=false npm run build --if-present
      - name: Run the tests
        run: cd controller && npm run test -a
          
