name: Deploy Frontend

on:
    push:
        branches: main
        
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: habit-heatmap
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "habit-heatmap-client"
          heroku_email: "ishmamf2003@gmail.com"
          appdir: "controller"
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
            node-version: '21'

      - name: Install dependencies
        run: cd controller && npm install
        
      - name: Build
        working-directory: controller/
        run: cd controller && npm run build
      
      - name: Run the tests
        working-directory: controller/
        run: cd controller && npm run test -a
          
